/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-rake_receiver
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RAKE_RECEIVER_API_H
#define INCLUDED_RAKE_RECEIVER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_rake_receiver_EXPORTS
#define RAKE_RECEIVER_API __GR_ATTR_EXPORT
#else
#define RAKE_RECEIVER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RAKE_RECEIVER_API_H */
